@baseUrl = https://localhost:5001/api

POST {{baseUrl}}/WishlistItems HTTP/1.1
Content-Type: application/json

{
    "name": "walk dog",
    "isComplete": true
}

###

GET {{baseUrl}}/WishlistItems/2 HTTP/1.1

###

GET {{baseUrl}}/WishlistItems HTTP/1.1.


###

PUT {{baseUrl}}/WishlistItems/2 HTTP/1.1
Content-Type: application/json

{
    "ID":2,
    "name":"feed dog",
    "isComplete":true
}

###
DELETE {{baseUrl}}/WishlistItems/2 HTTP/1.1
